---
# tasks file for azure_vm_creation
- name: creating a resource group
  azure_rm_resourcegroup:
    name: myrg
    state: present
    location: westus
- name: Create a virtual network
  azure_rm_virtualnetwork:
    resource_group: myrg
    name: myVirtualNetwork
    address_prefix_cidr: "10.1.0.0/24"
- name: Create a subnet
  azure_rm_subnet:
    resource_group: myrg
    virtual_network_name: myVirtualNetwork
    name: mySubnet
    address_prefixes_cidr: "10.1.0.0/16"
 - name: Create VM
   azure_rm_virtualmachine:
    resource_group: myrg
    name: myvm
    vm_size: Standard_D1_v2
    admin_username: cloud-user
    # admin_password: "{{admin_password }}"
    ssh_password_enabled: false
    public_ip_allocation_method: Dynamic
    open_ports:
      - 22
    ssh_public_keys:
      - path: /home/cloud-user/.ssh/authorized_keys
        key_data:  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI/kCjpHXYUQFYzo+XoIzhW0BbxcolIyBikfv7MDR00WAx6DYfNNPUGxBxwKs/ITUV8/h7uTrGOddBfNXcH7dJFK+/vbqEYEw2vRTmR7SYl0zI2dqzLOhNI7FAWG3QPhKnYAhZRn4JUuq+kFWEY5UTe5LdiUZB2Cek7/LSBPEPzhDNQTAO8qBu2rEet8RlpVeYOY47fIZVAEkVY4JFY1a+sSVTTup9VRB7r51re2HHv/YwlkVUeY2BjmaX7fyUUb/GIy3MXg1ZKF9LyexqTI5Cy4OOBonUjBwCquvWwN8GbolknqGPEcz9BDdLh3Vy9X0BWo5pgMn+bsqm3DHmqpcB root@localhost.localdomain
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.1'
      version: latest
    os_type: Linux

                                         


